credentials:
  usernames:
    admin:
      email: intel@moodlightintel.com
      name: Admin
      password: $2b$12$f0u/lE9K6c6nbGujUs4EWe53UWcLfp2WfelDlBEP6KpnD9Az7P/.6
      failed_login_attempts: 0
      logged_in: False

cookie:
  expiry_days: 30
  key: moodlight_auth_key_2025
  name: moodlight_auth
