#!/usr/bin/env python
"""
generate_brief.py
Generates an executive intelligence brief using Claude AI
"""

import os
import pandas as pd
from datetime import datetime, timezone
from anthropic import Anthropic
from dotenv import load_dotenv
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_email_brief(brief_text):
    """Send intelligence brief via email"""
    sender = os.getenv("EMAIL_ADDRESS")
    recipient = os.getenv("EMAIL_RECIPIENT")
    password = os.getenv("EMAIL_PASSWORD")
    
    if not all([sender, recipient, password]):
        print("Email credentials not configured. Skipping email.")
        return False
    
    msg = MIMEMultipart('alternative')
    msg['Subject'] = f'Intelligence Brief - {datetime.now(timezone.utc).strftime("%B %d, %Y")}'
    msg['From'] = sender
    msg['To'] = recipient
    
    # Create HTML version for better formatting
    html = f"""
    <html>
      <body style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto;">
        <h2 style="color: #1f77b4;">Daily Intelligence Brief</h2>
        <pre style="white-space: pre-wrap; font-family: 'Courier New', monospace; font-size: 14px;">
{brief_text}
        </pre>
        <hr>
        <p style="color: #666; font-size: 12px;">
          Generated by Moodlight Intelligence Platform<br>
          {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}
        </p>
      </body>
    </html>
    """
    
    msg.attach(MIMEText(html, 'html'))
    
    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(sender, password)
            server.send_message(msg)
        print(f"✅ Email sent to {recipient}")
        return True
    except Exception as e:
        print(f"❌ Email failed: {e}")
        return False

load_dotenv()

client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

def load_recent_data():
    """Load last 24 hours of intelligence data"""
    df = pd.read_csv("news_scored.csv")
    df['created_at'] = pd.to_datetime(df['created_at'], utc=True, errors='coerce')
    
    # Last 7 days
    cutoff = datetime.now(timezone.utc) - pd.Timedelta(days=7)
    recent = df[df['created_at'] >= cutoff]
    
    return recent

def prepare_intelligence_context(df):
    """Prepare context for AI briefing"""
    
    # Top topics by volume
    topic_counts = df['topic'].value_counts().head(5)
    
    # High intensity articles (4-5 severity)
    critical = df[df['intensity'] >= 4]
    
    # Geographic distribution
    country_counts = df['country'].value_counts().head(5)
    
    # Average intensity by topic
    topic_intensity = df.groupby('topic')['intensity'].mean().sort_values(ascending=False).head(5)
    
    context = f"""
INTELLIGENCE DATA SUMMARY (Last 24 Hours)
==========================================

TOP TOPICS BY VOLUME:
{topic_counts.to_string()}

HIGHEST INTENSITY TOPICS:
{topic_intensity.round(2).to_string()}

CRITICAL SEVERITY ARTICLES ({len(critical)} total):
{critical[['text', 'country', 'intensity']].head(10).to_string()}

GEOGRAPHIC DISTRIBUTION:
{country_counts.to_string()}

Total Articles Analyzed: {len(df)}
"""
    
    return context

def generate_brief(context):
    """Generate executive brief using Claude AI"""
    
    prompt = f"""You are a senior intelligence analyst preparing a daily executive brief for national security leadership.

Based on the following intelligence data, create a concise executive summary that:

1. Highlights the TOP 3 CRITICAL THREATS or developments
2. Identifies emerging patterns or trends
3. Provides ACTIONABLE INSIGHTS for decision-makers
4. Uses clear, direct language (no jargon)
5. Keeps it under 300 words

Format as:
EXECUTIVE INTELLIGENCE BRIEF - {datetime.now(timezone.utc).strftime("%B %d, %Y")}

KEY THREATS:
1. [Most critical]
2. [Second priority]
3. [Third priority]

EMERGING PATTERNS:
[2-3 sentences on trends]

RECOMMENDED ACTIONS:
[Bullet points]

DATA:
{context}
"""
    
    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=500,
        system="You are a senior intelligence analyst with 20 years of experience in national security and geopolitical risk assessment.",
        messages=[{"role": "user", "content": prompt}]
    )
    
    return response.content[0].text

def main():
    print("=" * 60)
    print("GENERATING EXECUTIVE INTELLIGENCE BRIEF")
    print("=" * 60)
    print()
    
    df = load_recent_data()
    
    if len(df) == 0:
        print("No recent data available for briefing.")
        return
    
    print(f"Analyzing {len(df)} intelligence reports...")
    print()
    
    context = prepare_intelligence_context(df)
    brief = generate_brief(context)
    
    print(brief)
    print()
    print("=" * 60)
    
    # Save to file
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    filename = f"intel_brief_{timestamp}.txt"
    
    with open(filename, 'w') as f:
        f.write(brief)
    
    print(f"Brief saved to: {filename}")

    # Send email
    send_email_brief(brief)

if __name__ == "__main__":
    main()
