"""
Email Delivery Service.
Handles sending strategic briefs and other emails via SMTP.
"""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import markdown

from app.config import get_settings

settings = get_settings()


def convert_markdown_to_html(md_content: str) -> str:
    """Convert markdown content to styled HTML."""
    html_body = markdown.markdown(md_content, extensions=['tables', 'fenced_code'])

    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
            }}
            h1, h2, h3 {{
                color: #1a1a1a;
                margin-top: 24px;
            }}
            h1 {{ font-size: 28px; border-bottom: 2px solid #FF4B4B; padding-bottom: 10px; }}
            h2 {{ font-size: 22px; color: #FF4B4B; }}
            h3 {{ font-size: 18px; }}
            p {{ margin: 12px 0; }}
            ul, ol {{ margin: 12px 0; padding-left: 24px; }}
            li {{ margin: 6px 0; }}
            strong {{ color: #1a1a1a; }}
            blockquote {{
                border-left: 4px solid #FF4B4B;
                margin: 16px 0;
                padding: 12px 20px;
                background: #f9f9f9;
            }}
            code {{
                background: #f4f4f4;
                padding: 2px 6px;
                border-radius: 4px;
                font-family: Monaco, Consolas, monospace;
            }}
            hr {{
                border: none;
                border-top: 1px solid #ddd;
                margin: 24px 0;
            }}
            .footer {{
                margin-top: 40px;
                padding-top: 20px;
                border-top: 1px solid #ddd;
                font-size: 14px;
                color: #666;
            }}
        </style>
    </head>
    <body>
        {html_body}
        <div class="footer">
            <p>This brief was generated by <strong>Moodlight Intelligence</strong></p>
            <p>For questions or feedback, contact <a href="mailto:intel@moodlightintel.com">intel@moodlightintel.com</a></p>
        </div>
    </body>
    </html>
    """


async def send_brief_email(
    to_email: str,
    brief_content: str,
    user_need: str,
    frameworks_used: list[str]
) -> bool:
    """
    Send a strategic brief via email.

    Args:
        to_email: Recipient email address
        brief_content: The markdown content of the brief
        user_need: The original request that generated the brief
        frameworks_used: List of framework names applied

    Returns:
        True if email was sent successfully, False otherwise
    """
    if not settings.smtp_host or not settings.smtp_user:
        print("SMTP not configured, skipping email delivery")
        return False

    try:
        # Create message
        msg = MIMEMultipart('alternative')
        msg['Subject'] = f"Moodlight Strategic Brief: {user_need[:50]}..."
        msg['From'] = settings.smtp_from or settings.smtp_user
        msg['To'] = to_email

        # Plain text version
        text_content = f"""
MOODLIGHT STRATEGIC BRIEF
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}

REQUEST: {user_need}

FRAMEWORKS APPLIED: {', '.join(frameworks_used)}

---

{brief_content}

---
This brief was generated by Moodlight Intelligence.
For questions, contact intel@moodlightintel.com
"""

        # HTML version
        html_header = f"""
<h1>Strategic Brief</h1>
<p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
<p><strong>Request:</strong> {user_need}</p>
<p><strong>Frameworks Applied:</strong> {', '.join(frameworks_used)}</p>
<hr>
"""
        html_content = convert_markdown_to_html(html_header + brief_content)

        # Attach both versions
        part1 = MIMEText(text_content, 'plain')
        part2 = MIMEText(html_content, 'html')
        msg.attach(part1)
        msg.attach(part2)

        # Send email
        with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
            if settings.smtp_port == 587:
                server.starttls()
            server.login(settings.smtp_user, settings.smtp_password)
            server.send_message(msg)

        return True

    except Exception as e:
        print(f"Email delivery failed: {e}")
        return False


async def send_welcome_email(to_email: str, username: str) -> bool:
    """Send welcome email to new users."""
    if not settings.smtp_host or not settings.smtp_user:
        return False

    try:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = "Welcome to Moodlight Intelligence"
        msg['From'] = settings.smtp_from or settings.smtp_user
        msg['To'] = to_email

        text_content = f"""
Welcome to Moodlight, {username}!

Your account has been created and you're ready to start exploring cultural intelligence.

Key features available to you:
- Real-time empathy and emotion tracking
- Strategic brief generation with AI
- Brand analysis with VLDS metrics
- Prediction market insights

Log in at: {settings.app_url}

Questions? Contact intel@moodlightintel.com
"""

        html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; }}
        .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #FF4B4B; }}
        .cta {{ display: inline-block; padding: 12px 24px; background: #FF4B4B; color: white; text-decoration: none; border-radius: 6px; margin: 20px 0; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Welcome to Moodlight!</h1>
        <p>Hi {username},</p>
        <p>Your account has been created and you're ready to start exploring cultural intelligence.</p>
        <p><strong>Key features available to you:</strong></p>
        <ul>
            <li>Real-time empathy and emotion tracking</li>
            <li>Strategic brief generation with AI</li>
            <li>Brand analysis with VLDS metrics</li>
            <li>Prediction market insights</li>
        </ul>
        <a href="{settings.app_url}" class="cta">Log In to Moodlight</a>
        <p style="color: #666; font-size: 14px;">Questions? Contact <a href="mailto:intel@moodlightintel.com">intel@moodlightintel.com</a></p>
    </div>
</body>
</html>
"""

        part1 = MIMEText(text_content, 'plain')
        part2 = MIMEText(html_content, 'html')
        msg.attach(part1)
        msg.attach(part2)

        with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
            if settings.smtp_port == 587:
                server.starttls()
            server.login(settings.smtp_user, settings.smtp_password)
            server.send_message(msg)

        return True

    except Exception as e:
        print(f"Welcome email failed: {e}")
        return False
